// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc4Bc8kmRg-TzNf1xkW3X-DGxd014GdWg',
    appId: '1:766092476818:web:3fc5763ec285923738414b',
    messagingSenderId: '766092476818',
    projectId: 'isi-events',
    authDomain: 'isi-events.firebaseapp.com',
    storageBucket: 'isi-events.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDovANNp7KYw2oqDAN5Xg6Vf0IgO27AGBE',
    appId: '1:766092476818:android:eb04e7b1a732b2c638414b',
    messagingSenderId: '766092476818',
    projectId: 'isi-events',
    storageBucket: 'isi-events.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHh3luxOmeuF9TsOeF-eeE7r_UskbGB4I',
    appId: '1:766092476818:ios:560ef4e55a5e142338414b',
    messagingSenderId: '766092476818',
    projectId: 'isi-events',
    storageBucket: 'isi-events.appspot.com',
    iosBundleId: 'com.example.isiEvent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHh3luxOmeuF9TsOeF-eeE7r_UskbGB4I',
    appId: '1:766092476818:ios:560ef4e55a5e142338414b',
    messagingSenderId: '766092476818',
    projectId: 'isi-events',
    storageBucket: 'isi-events.appspot.com',
    iosBundleId: 'com.example.isiEvent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc4Bc8kmRg-TzNf1xkW3X-DGxd014GdWg',
    appId: '1:766092476818:web:38fe50df8c8bdfee38414b',
    messagingSenderId: '766092476818',
    projectId: 'isi-events',
    authDomain: 'isi-events.firebaseapp.com',
    storageBucket: 'isi-events.appspot.com',
  );
}
